services:
  # Pythonスクリプトを実行するサービス
  init-script:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["ash", "-c", "python app.py"] # スクリプトの実行コマンド
    restart: "no" # 一度だけ実行する

  # サーバーサービス
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["tail", "-f", "/dev/null"] # ここにサーバーの実行コマンド
    restart: always
    ports:
      - 5000:5000
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
